# Generated by Django 3.2 on 2021-04-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addmedicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduser',
            name='id',
        ),
        migrations.AlterField(
            model_name='adduser',
            name='name',
            field=models.CharField(max_length=122, primary_key=True, serialize=False),
        ),
    ]
